### ISSUE TITLE
Add data download button on section and indicator levels

### ISSUE THREAD

**Issue by plantfansam** [sunlightlabs/mptindicators#103]
language should read "Download full dataset"

**Comment by plantfansam** [comment]
closed here: 7a0c95293049535d8819bd637623d1fc4782cd26

**Comment by plantfansam** [comment]
@cweber can you take a look and make sure this looks alright? Perhaps the download sections need an `h3`

**Comment by cweber** [comment]
Actually, yes. I'd like an h3 in there like some of the others, plus it lost some spacing that was there before. Adding that back in too.
