### ISSUE TITLE
Max-width on top-bar nav

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/mptindicators#40]

**Comment by cweber** [comment]
Fixed the max width thing so now stuff doesn't just disappear, but there's a media query that I can't figure out how to change. Should be controlled with these lines, but some dependency is getting in the way and breaking something.

@handlers Could you take a look?

Line 1465-6 in _settings.scss
![screen shot 2015-07-09 at 6 44 26 pm](https://cloud.githubusercontent.com/assets/417657/8608638/a0b6b314-266a-11e5-9b9b-1cb72a88fcce.png)

**Comment by plantfansam** [comment]
closed 3d6f8acd61830a729566ccd0b3e55d3f19448949
