### ISSUE TITLE
Make 'collapsed' the default state for all but the first category/subcategory on country pages

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/mptindicators#65]

**Comment by jcarbaugh** [comment]
Got this confused with nav state, it's page content instead.

**Comment by plantfansam** [comment]
![image](https://api.monosnap.com/rpc/file/download?id=SXi7bO8u0TQAf5P1XaJ1BHNKm6MoFL)

**Comment by plantfansam** [comment]
![image](https://api.monosnap.com/rpc/file/download?id=Yyd0HpmJCkK7YrDg4PfEdYdSW0Qjtx)
