### ISSUE TITLE
Check for things that are supposed to be linked in Methodology and FAQ

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/mptindicators#71]

**Comment by cweber** [comment]
Added full-methodology_mpt-Campaign-finance-indicators.pdf to static/pdfs. Needs to be linked on Methodology page ones the updated copy is in.

**Comment by plantfansam** [comment]
I added the link to the methodology page. There may be other things to link to, but I didn't see intra-site linking that was obvious.
