### ISSUE TITLE
Download Data link to zip

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/mptindicators#72]
Download data link will always link to a zip of the full data set (csv and formatted spreadsheet?)

**Comment by cweber** [comment]
I'm assigning this one to you for now since the first step is getting the data formatted correctly, zipped and uploaded somewhere.

**Comment by plantfansam** [comment]
There is a zip file with this data up on s3 now. The data comes from Michael's email of 6/22.

**Comment by plantfansam** [comment]
this is up. see 7a0c95293049535d8819bd637623d1fc4782cd26
