### ISSUE TITLE
Add note style to side bar for 'no scores' on scoreless indicators

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/mptindicators#74]

**Comment by cweber** [comment]
@handlers I added some draft language/styling for this. It needs to be triggered to only show up on "Open Question" indicators

**Comment by plantfansam** [comment]
@cweber can you point me to the language/styles

**Comment by plantfansam** [comment]
![image](https://api.monosnap.com/rpc/file/download?id=wcqY25rZkWuT40WakgF4qX2fvFbajQ)

**Comment by plantfansam** [comment]
This is only showing on open question indicators, now. See: bcea3e4f212655ce989b8982e20d3b8c5890f91e
