### ISSUE TITLE
Change 'United States' to 'United States of America'

### ISSUE THREAD

**Issue by cweber** [sunlightlabs/mptindicators#79]

**Comment by jcarbaugh** [comment]
This will be done, but it'll have to be done after data loading. A lot of the data matching during loading is done with matching on country name. After that's all done, just log in to the admin and change the name of the US.

**Comment by plantfansam** [comment]
This refers to the Countries nav (and anywhere the country name shows up more generally)

**Comment by plantfansam** [comment]
changed in production database
